---
galaxy_info:
  role_name: install
  author: kudato
  description: Install Fedora CoreOS
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Fedora CoreOS
      versions:
        - ">=43"

dependencies: []

